//This file was generated by CssMagicMaker
import React from "react";
import PropTypes from "prop-types";
import scaleUpCenter from "./src/basic/scale-up/scaleUpCenter.jsx";
import scaleUpTop from "./src/basic/scale-up/scaleUpTop.jsx";
import scaleUpTr from "./src/basic/scale-up/scaleUpTr.jsx";
import scaleUpRight from "./src/basic/scale-up/scaleUpRight.jsx";
import scaleUpBr from "./src/basic/scale-up/scaleUpBr.jsx";
import scaleUpBottom from "./src/basic/scale-up/scaleUpBottom.jsx";
import scaleUpBl from "./src/basic/scale-up/scaleUpBl.jsx";
import scaleUpLeft from "./src/basic/scale-up/scaleUpLeft.jsx";
import scaleUpTl from "./src/basic/scale-up/scaleUpTl.jsx";
import scaleUpHorCenter from "./src/basic/scale-up/scaleUpHorCenter.jsx";
import scaleUpHorLeft from "./src/basic/scale-up/scaleUpHorLeft.jsx";
import scaleUpHorRight from "./src/basic/scale-up/scaleUpHorRight.jsx";
import scaleUpVerCenter from "./src/basic/scale-up/scaleUpVerCenter.jsx";
import scaleUpVerTop from "./src/basic/scale-up/scaleUpVerTop.jsx";
import scaleUpVerBottom from "./src/basic/scale-up/scaleUpVerBottom.jsx";
import scaleDownCenter from "./src/basic/scale-down/scaleDownCenter.jsx";
import scaleDownTop from "./src/basic/scale-down/scaleDownTop.jsx";
import scaleDownTr from "./src/basic/scale-down/scaleDownTr.jsx";
import scaleDownRight from "./src/basic/scale-down/scaleDownRight.jsx";
import scaleDownBr from "./src/basic/scale-down/scaleDownBr.jsx";
import scaleDownBottom from "./src/basic/scale-down/scaleDownBottom.jsx";
import scaleDownBl from "./src/basic/scale-down/scaleDownBl.jsx";
import scaleDownLeft from "./src/basic/scale-down/scaleDownLeft.jsx";
import scaleDownTl from "./src/basic/scale-down/scaleDownTl.jsx";
import scaleDownHorCenter from "./src/basic/scale-down/scaleDownHorCenter.jsx";
import scaleDownHorLeft from "./src/basic/scale-down/scaleDownHorLeft.jsx";
import scaleDownHorRight from "./src/basic/scale-down/scaleDownHorRight.jsx";
import scaleDownVerCenter from "./src/basic/scale-down/scaleDownVerCenter.jsx";
import scaleDownVerTop from "./src/basic/scale-down/scaleDownVerTop.jsx";
import scaleDownVerBottom from "./src/basic/scale-down/scaleDownVerBottom.jsx";
import rotateCenter from "./src/basic/rotate/rotateCenter.jsx";
import rotateTop from "./src/basic/rotate/rotateTop.jsx";
import rotateTr from "./src/basic/rotate/rotateTr.jsx";
import rotateRight from "./src/basic/rotate/rotateRight.jsx";
import rotateBr from "./src/basic/rotate/rotateBr.jsx";
import rotateBottom from "./src/basic/rotate/rotateBottom.jsx";
import rotateBl from "./src/basic/rotate/rotateBl.jsx";
import rotateLeft from "./src/basic/rotate/rotateLeft.jsx";
import rotateTl from "./src/basic/rotate/rotateTl.jsx";
import rotateHorCenter from "./src/basic/rotate/rotateHorCenter.jsx";
import rotateHorTop from "./src/basic/rotate/rotateHorTop.jsx";
import rotateHorBottom from "./src/basic/rotate/rotateHorBottom.jsx";
import rotateVertCenter from "./src/basic/rotate/rotateVertCenter.jsx";
import rotateVertLeft from "./src/basic/rotate/rotateVertLeft.jsx";
import rotateVertRight from "./src/basic/rotate/rotateVertRight.jsx";
import rotateDiagonal1 from "./src/basic/rotate/rotateDiagonal1.jsx";
import rotateDiagonal2 from "./src/basic/rotate/rotateDiagonal2.jsx";
import rotateDiagonalTr from "./src/basic/rotate/rotateDiagonalTr.jsx";
import rotateDiagonalBr from "./src/basic/rotate/rotateDiagonalBr.jsx";
import rotateDiagonalBl from "./src/basic/rotate/rotateDiagonalBl.jsx";
import rotateDiagonalTl from "./src/basic/rotate/rotateDiagonalTl.jsx";
import rotateScaleUp from "./src/basic/rotate-scale/rotateScaleUp.jsx";
import rotateScaleDown from "./src/basic/rotate-scale/rotateScaleDown.jsx";
import rotateScaleUpHor from "./src/basic/rotate-scale/rotateScaleUpHor.jsx";
import rotateScaleDownHor from "./src/basic/rotate-scale/rotateScaleDownHor.jsx";
import rotateScaleUpVer from "./src/basic/rotate-scale/rotateScaleUpVer.jsx";
import rotateScaleDownVer from "./src/basic/rotate-scale/rotateScaleDownVer.jsx";
import rotateScaleUpDiag1 from "./src/basic/rotate-scale/rotateScaleUpDiag1.jsx";
import rotateScaleDownDiag1 from "./src/basic/rotate-scale/rotateScaleDownDiag1.jsx";
import rotateScaleUpDiag2 from "./src/basic/rotate-scale/rotateScaleUpDiag2.jsx";
import rotateScaleDownDiag2 from "./src/basic/rotate-scale/rotateScaleDownDiag2.jsx";
import rotate90Cw from "./src/basic/rotate-90/rotate90Cw.jsx";
import rotate90Ccw from "./src/basic/rotate-90/rotate90Ccw.jsx";
import rotate90TopCw from "./src/basic/rotate-90/rotate90TopCw.jsx";
import rotate90TopCcw from "./src/basic/rotate-90/rotate90TopCcw.jsx";
import rotate90TrCw from "./src/basic/rotate-90/rotate90TrCw.jsx";
import rotate90TrCcw from "./src/basic/rotate-90/rotate90TrCcw.jsx";
import rotate90RightCw from "./src/basic/rotate-90/rotate90RightCw.jsx";
import rotate90RightCcw from "./src/basic/rotate-90/rotate90RightCcw.jsx";
import rotate90BrCw from "./src/basic/rotate-90/rotate90BrCw.jsx";
import rotate90BrCcw from "./src/basic/rotate-90/rotate90BrCcw.jsx";
import rotate90BottomCw from "./src/basic/rotate-90/rotate90BottomCw.jsx";
import rotate90BottomCcw from "./src/basic/rotate-90/rotate90BottomCcw.jsx";
import rotate90BlCw from "./src/basic/rotate-90/rotate90BlCw.jsx";
import rotate90BlCcw from "./src/basic/rotate-90/rotate90BlCcw.jsx";
import rotate90LeftCw from "./src/basic/rotate-90/rotate90LeftCw.jsx";
import rotate90LeftCcw from "./src/basic/rotate-90/rotate90LeftCcw.jsx";
import rotate90TlCw from "./src/basic/rotate-90/rotate90TlCw.jsx";
import rotate90TlCcw from "./src/basic/rotate-90/rotate90TlCcw.jsx";
import rotate90HorizontalFwd from "./src/basic/rotate-90/rotate90HorizontalFwd.jsx";
import rotate90HorizontalBck from "./src/basic/rotate-90/rotate90HorizontalBck.jsx";
import rotate90VerticalFwd from "./src/basic/rotate-90/rotate90VerticalFwd.jsx";
import rotate90VerticalBck from "./src/basic/rotate-90/rotate90VerticalBck.jsx";
import flipHorizontalBottom from "./src/basic/flip/flipHorizontalBottom.jsx";
import flipHorizontalTop from "./src/basic/flip/flipHorizontalTop.jsx";
import flipHorizontalBck from "./src/basic/flip/flipHorizontalBck.jsx";
import flipHorizontalFwd from "./src/basic/flip/flipHorizontalFwd.jsx";
import flipVerticalRight from "./src/basic/flip/flipVerticalRight.jsx";
import flipVerticalLeft from "./src/basic/flip/flipVerticalLeft.jsx";
import flipVerticalBck from "./src/basic/flip/flipVerticalBck.jsx";
import flipVerticalFwd from "./src/basic/flip/flipVerticalFwd.jsx";
import flipDiagonal1Tr from "./src/basic/flip/flipDiagonal1Tr.jsx";
import flipDiagonal1Bl from "./src/basic/flip/flipDiagonal1Bl.jsx";
import flipDiagonal1Bck from "./src/basic/flip/flipDiagonal1Bck.jsx";
import flipDiagonal1Fwd from "./src/basic/flip/flipDiagonal1Fwd.jsx";
import flipDiagonal2Br from "./src/basic/flip/flipDiagonal2Br.jsx";
import flipDiagonal2Tl from "./src/basic/flip/flipDiagonal2Tl.jsx";
import flipDiagonal2Bck from "./src/basic/flip/flipDiagonal2Bck.jsx";
import flipDiagonal2Fwd from "./src/basic/flip/flipDiagonal2Fwd.jsx";
import flip2HorTop1 from "./src/basic/flip-2/flip2HorTop1.jsx";
import flip2HorTop2 from "./src/basic/flip-2/flip2HorTop2.jsx";
import flip2HorTopBck from "./src/basic/flip-2/flip2HorTopBck.jsx";
import flip2HorTopFwd from "./src/basic/flip-2/flip2HorTopFwd.jsx";
import flip2VerRight1 from "./src/basic/flip-2/flip2VerRight1.jsx";
import flip2VerRight2 from "./src/basic/flip-2/flip2VerRight2.jsx";
import flip2VerRightBck from "./src/basic/flip-2/flip2VerRightBck.jsx";
import flip2VerRightFwd from "./src/basic/flip-2/flip2VerRightFwd.jsx";
import flip2HorBottom1 from "./src/basic/flip-2/flip2HorBottom1.jsx";
import flip2HorBottom2 from "./src/basic/flip-2/flip2HorBottom2.jsx";
import flip2HorBottomBck from "./src/basic/flip-2/flip2HorBottomBck.jsx";
import flip2HorBottomFwd from "./src/basic/flip-2/flip2HorBottomFwd.jsx";
import flip2VerLeft1 from "./src/basic/flip-2/flip2VerLeft1.jsx";
import flip2VerLeft2 from "./src/basic/flip-2/flip2VerLeft2.jsx";
import flip2VerLeftBck from "./src/basic/flip-2/flip2VerLeftBck.jsx";
import flip2VerLeftFwd from "./src/basic/flip-2/flip2VerLeftFwd.jsx";
import flipScaleUpHor from "./src/basic/flip-scale/flipScaleUpHor.jsx";
import flipScaleDownHor from "./src/basic/flip-scale/flipScaleDownHor.jsx";
import flipScaleUpVer from "./src/basic/flip-scale/flipScaleUpVer.jsx";
import flipScaleDownVer from "./src/basic/flip-scale/flipScaleDownVer.jsx";
import flipScaleUpDiag1 from "./src/basic/flip-scale/flipScaleUpDiag1.jsx";
import flipScaleDownDiag1 from "./src/basic/flip-scale/flipScaleDownDiag1.jsx";
import flipScaleUpDiag2 from "./src/basic/flip-scale/flipScaleUpDiag2.jsx";
import flipScaleDownDiag2 from "./src/basic/flip-scale/flipScaleDownDiag2.jsx";
import flipScale2HorTop from "./src/basic/flip-scale-2/flipScale2HorTop.jsx";
import flipScale2VerRight from "./src/basic/flip-scale-2/flipScale2VerRight.jsx";
import flipScale2HorBottom from "./src/basic/flip-scale-2/flipScale2HorBottom.jsx";
import flipScale2VerLeft from "./src/basic/flip-scale-2/flipScale2VerLeft.jsx";
import swingTopFwd from "./src/basic/swing/swingTopFwd.jsx";
import swingTopBck from "./src/basic/swing/swingTopBck.jsx";
import swingTopRightFwd from "./src/basic/swing/swingTopRightFwd.jsx";
import swingTopRightBck from "./src/basic/swing/swingTopRightBck.jsx";
import swingRightFwd from "./src/basic/swing/swingRightFwd.jsx";
import swingRightBck from "./src/basic/swing/swingRightBck.jsx";
import swingBottomRightFwd from "./src/basic/swing/swingBottomRightFwd.jsx";
import swingBottomRightBck from "./src/basic/swing/swingBottomRightBck.jsx";
import swingBottomFwd from "./src/basic/swing/swingBottomFwd.jsx";
import swingBottomBck from "./src/basic/swing/swingBottomBck.jsx";
import swingBottomLeftFwd from "./src/basic/swing/swingBottomLeftFwd.jsx";
import swingBottomLeftBck from "./src/basic/swing/swingBottomLeftBck.jsx";
import swingLeftFwd from "./src/basic/swing/swingLeftFwd.jsx";
import swingLeftBck from "./src/basic/swing/swingLeftBck.jsx";
import swingTopLeftFwd from "./src/basic/swing/swingTopLeftFwd.jsx";
import swingTopLeftBck from "./src/basic/swing/swingTopLeftBck.jsx";
import slideTop from "./src/basic/slide/slideTop.jsx";
import slideTr from "./src/basic/slide/slideTr.jsx";
import slideRight from "./src/basic/slide/slideRight.jsx";
import slideBr from "./src/basic/slide/slideBr.jsx";
import slideBottom from "./src/basic/slide/slideBottom.jsx";
import slideBl from "./src/basic/slide/slideBl.jsx";
import slideLeft from "./src/basic/slide/slideLeft.jsx";
import slideTl from "./src/basic/slide/slideTl.jsx";
import slideBckCenter from "./src/basic/slide-bck/slideBckCenter.jsx";
import slideBckTop from "./src/basic/slide-bck/slideBckTop.jsx";
import slideBckTr from "./src/basic/slide-bck/slideBckTr.jsx";
import slideBckRight from "./src/basic/slide-bck/slideBckRight.jsx";
import slideBckBr from "./src/basic/slide-bck/slideBckBr.jsx";
import slideBckBottom from "./src/basic/slide-bck/slideBckBottom.jsx";
import slideBckBl from "./src/basic/slide-bck/slideBckBl.jsx";
import slideBckLeft from "./src/basic/slide-bck/slideBckLeft.jsx";
import slideBckTl from "./src/basic/slide-bck/slideBckTl.jsx";
import slideFwdCenter from "./src/basic/slide-fwd/slideFwdCenter.jsx";
import slideFwdTop from "./src/basic/slide-fwd/slideFwdTop.jsx";
import slideFwdTr from "./src/basic/slide-fwd/slideFwdTr.jsx";
import slideFwdRight from "./src/basic/slide-fwd/slideFwdRight.jsx";
import slideFwdBr from "./src/basic/slide-fwd/slideFwdBr.jsx";
import slideFwdBottom from "./src/basic/slide-fwd/slideFwdBottom.jsx";
import slideFwdBl from "./src/basic/slide-fwd/slideFwdBl.jsx";
import slideFwdLeft from "./src/basic/slide-fwd/slideFwdLeft.jsx";
import slideFwdTl from "./src/basic/slide-fwd/slideFwdTl.jsx";
import slideRotateHorTop from "./src/basic/slide-rotate/slideRotateHorTop.jsx";
import slideRotateHorTBck from "./src/basic/slide-rotate/slideRotateHorTBck.jsx";
import slideRotateHorTFwd from "./src/basic/slide-rotate/slideRotateHorTFwd.jsx";
import slideRotateVerRight from "./src/basic/slide-rotate/slideRotateVerRight.jsx";
import slideRotateVerRBck from "./src/basic/slide-rotate/slideRotateVerRBck.jsx";
import slideRotateVerRFwd from "./src/basic/slide-rotate/slideRotateVerRFwd.jsx";
import slideRotateHorBottom from "./src/basic/slide-rotate/slideRotateHorBottom.jsx";
import slideRotateHorBBck from "./src/basic/slide-rotate/slideRotateHorBBck.jsx";
import slideRotateHorBFwd from "./src/basic/slide-rotate/slideRotateHorBFwd.jsx";
import slideRotateVerLeft from "./src/basic/slide-rotate/slideRotateVerLeft.jsx";
import slideRotateVerLBck from "./src/basic/slide-rotate/slideRotateVerLBck.jsx";
import slideRotateVerLFwd from "./src/basic/slide-rotate/slideRotateVerLFwd.jsx";
import shadowDropCenter from "./src/basic/shadow-drop/shadowDropCenter.jsx";
import shadowDropTop from "./src/basic/shadow-drop/shadowDropTop.jsx";
import shadowDropRight from "./src/basic/shadow-drop/shadowDropRight.jsx";
import shadowDropBottom from "./src/basic/shadow-drop/shadowDropBottom.jsx";
import shadowDropLeft from "./src/basic/shadow-drop/shadowDropLeft.jsx";
import shadowDropLr from "./src/basic/shadow-drop/shadowDropLr.jsx";
import shadowDropTb from "./src/basic/shadow-drop/shadowDropTb.jsx";
import shadowDropTr from "./src/basic/shadow-drop/shadowDropTr.jsx";
import shadowDropBr from "./src/basic/shadow-drop/shadowDropBr.jsx";
import shadowDropBl from "./src/basic/shadow-drop/shadowDropBl.jsx";
import shadowDropTl from "./src/basic/shadow-drop/shadowDropTl.jsx";
import shadowDrop2Center from "./src/basic/shadow-drop-2/shadowDrop2Center.jsx";
import shadowDrop2Top from "./src/basic/shadow-drop-2/shadowDrop2Top.jsx";
import shadowDrop2Right from "./src/basic/shadow-drop-2/shadowDrop2Right.jsx";
import shadowDrop2Bottom from "./src/basic/shadow-drop-2/shadowDrop2Bottom.jsx";
import shadowDrop2Left from "./src/basic/shadow-drop-2/shadowDrop2Left.jsx";
import shadowDrop2Lr from "./src/basic/shadow-drop-2/shadowDrop2Lr.jsx";
import shadowDrop2Tb from "./src/basic/shadow-drop-2/shadowDrop2Tb.jsx";
import shadowDrop2Tr from "./src/basic/shadow-drop-2/shadowDrop2Tr.jsx";
import shadowDrop2Br from "./src/basic/shadow-drop-2/shadowDrop2Br.jsx";
import shadowDrop2Bl from "./src/basic/shadow-drop-2/shadowDrop2Bl.jsx";
import shadowDrop2Tl from "./src/basic/shadow-drop-2/shadowDrop2Tl.jsx";
import shadowPopTr from "./src/basic/shadow-pop/shadowPopTr.jsx";
import shadowPopBr from "./src/basic/shadow-pop/shadowPopBr.jsx";
import shadowPopBl from "./src/basic/shadow-pop/shadowPopBl.jsx";
import shadowPopTl from "./src/basic/shadow-pop/shadowPopTl.jsx";
import shadowInsetCenter from "./src/basic/shadow-inset/shadowInsetCenter.jsx";
import shadowInsetTop from "./src/basic/shadow-inset/shadowInsetTop.jsx";
import shadowInsetRight from "./src/basic/shadow-inset/shadowInsetRight.jsx";
import shadowInsetBottom from "./src/basic/shadow-inset/shadowInsetBottom.jsx";
import shadowInsetLeft from "./src/basic/shadow-inset/shadowInsetLeft.jsx";
import shadowInsetLr from "./src/basic/shadow-inset/shadowInsetLr.jsx";
import shadowInsetTb from "./src/basic/shadow-inset/shadowInsetTb.jsx";
import shadowInsetTr from "./src/basic/shadow-inset/shadowInsetTr.jsx";
import shadowInsetBr from "./src/basic/shadow-inset/shadowInsetBr.jsx";
import shadowInsetBl from "./src/basic/shadow-inset/shadowInsetBl.jsx";
import shadowInsetTl from "./src/basic/shadow-inset/shadowInsetTl.jsx";
export {
  scaleUpCenter,
  scaleUpTop,
  scaleUpTr,
  scaleUpRight,
  scaleUpBr,
  scaleUpBottom,
  scaleUpBl,
  scaleUpLeft,
  scaleUpTl,
  scaleUpHorCenter,
  scaleUpHorLeft,
  scaleUpHorRight,
  scaleUpVerCenter,
  scaleUpVerTop,
  scaleUpVerBottom,
  scaleDownCenter,
  scaleDownTop,
  scaleDownTr,
  scaleDownRight,
  scaleDownBr,
  scaleDownBottom,
  scaleDownBl,
  scaleDownLeft,
  scaleDownTl,
  scaleDownHorCenter,
  scaleDownHorLeft,
  scaleDownHorRight,
  scaleDownVerCenter,
  scaleDownVerTop,
  scaleDownVerBottom,
  rotateCenter,
  rotateTop,
  rotateTr,
  rotateRight,
  rotateBr,
  rotateBottom,
  rotateBl,
  rotateLeft,
  rotateTl,
  rotateHorCenter,
  rotateHorTop,
  rotateHorBottom,
  rotateVertCenter,
  rotateVertLeft,
  rotateVertRight,
  rotateDiagonal1,
  rotateDiagonal2,
  rotateDiagonalTr,
  rotateDiagonalBr,
  rotateDiagonalBl,
  rotateDiagonalTl,
  rotateScaleUp,
  rotateScaleDown,
  rotateScaleUpHor,
  rotateScaleDownHor,
  rotateScaleUpVer,
  rotateScaleDownVer,
  rotateScaleUpDiag1,
  rotateScaleDownDiag1,
  rotateScaleUpDiag2,
  rotateScaleDownDiag2,
  rotate90Cw,
  rotate90Ccw,
  rotate90TopCw,
  rotate90TopCcw,
  rotate90TrCw,
  rotate90TrCcw,
  rotate90RightCw,
  rotate90RightCcw,
  rotate90BrCw,
  rotate90BrCcw,
  rotate90BottomCw,
  rotate90BottomCcw,
  rotate90BlCw,
  rotate90BlCcw,
  rotate90LeftCw,
  rotate90LeftCcw,
  rotate90TlCw,
  rotate90TlCcw,
  rotate90HorizontalFwd,
  rotate90HorizontalBck,
  rotate90VerticalFwd,
  rotate90VerticalBck,
  flipHorizontalBottom,
  flipHorizontalTop,
  flipHorizontalBck,
  flipHorizontalFwd,
  flipVerticalRight,
  flipVerticalLeft,
  flipVerticalBck,
  flipVerticalFwd,
  flipDiagonal1Tr,
  flipDiagonal1Bl,
  flipDiagonal1Bck,
  flipDiagonal1Fwd,
  flipDiagonal2Br,
  flipDiagonal2Tl,
  flipDiagonal2Bck,
  flipDiagonal2Fwd,
  flip2HorTop1,
  flip2HorTop2,
  flip2HorTopBck,
  flip2HorTopFwd,
  flip2VerRight1,
  flip2VerRight2,
  flip2VerRightBck,
  flip2VerRightFwd,
  flip2HorBottom1,
  flip2HorBottom2,
  flip2HorBottomBck,
  flip2HorBottomFwd,
  flip2VerLeft1,
  flip2VerLeft2,
  flip2VerLeftBck,
  flip2VerLeftFwd,
  flipScaleUpHor,
  flipScaleDownHor,
  flipScaleUpVer,
  flipScaleDownVer,
  flipScaleUpDiag1,
  flipScaleDownDiag1,
  flipScaleUpDiag2,
  flipScaleDownDiag2,
  flipScale2HorTop,
  flipScale2VerRight,
  flipScale2HorBottom,
  flipScale2VerLeft,
  swingTopFwd,
  swingTopBck,
  swingTopRightFwd,
  swingTopRightBck,
  swingRightFwd,
  swingRightBck,
  swingBottomRightFwd,
  swingBottomRightBck,
  swingBottomFwd,
  swingBottomBck,
  swingBottomLeftFwd,
  swingBottomLeftBck,
  swingLeftFwd,
  swingLeftBck,
  swingTopLeftFwd,
  swingTopLeftBck,
  slideTop,
  slideTr,
  slideRight,
  slideBr,
  slideBottom,
  slideBl,
  slideLeft,
  slideTl,
  slideBckCenter,
  slideBckTop,
  slideBckTr,
  slideBckRight,
  slideBckBr,
  slideBckBottom,
  slideBckBl,
  slideBckLeft,
  slideBckTl,
  slideFwdCenter,
  slideFwdTop,
  slideFwdTr,
  slideFwdRight,
  slideFwdBr,
  slideFwdBottom,
  slideFwdBl,
  slideFwdLeft,
  slideFwdTl,
  slideRotateHorTop,
  slideRotateHorTBck,
  slideRotateHorTFwd,
  slideRotateVerRight,
  slideRotateVerRBck,
  slideRotateVerRFwd,
  slideRotateHorBottom,
  slideRotateHorBBck,
  slideRotateHorBFwd,
  slideRotateVerLeft,
  slideRotateVerLBck,
  slideRotateVerLFwd,
  shadowDropCenter,
  shadowDropTop,
  shadowDropRight,
  shadowDropBottom,
  shadowDropLeft,
  shadowDropLr,
  shadowDropTb,
  shadowDropTr,
  shadowDropBr,
  shadowDropBl,
  shadowDropTl,
  shadowDrop2Center,
  shadowDrop2Top,
  shadowDrop2Right,
  shadowDrop2Bottom,
  shadowDrop2Left,
  shadowDrop2Lr,
  shadowDrop2Tb,
  shadowDrop2Tr,
  shadowDrop2Br,
  shadowDrop2Bl,
  shadowDrop2Tl,
  shadowPopTr,
  shadowPopBr,
  shadowPopBl,
  shadowPopTl,
  shadowInsetCenter,
  shadowInsetTop,
  shadowInsetRight,
  shadowInsetBottom,
  shadowInsetLeft,
  shadowInsetLr,
  shadowInsetTb,
  shadowInsetTr,
  shadowInsetBr,
  shadowInsetBl,
  shadowInsetTl
};
